FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

ARG VITE_GEMINI_API_KEY
ARG VITE_BASE_URL

RUN VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY VITE_BASE_URL=$VITE_BASE_URL

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY ./ssl/ /etc/nginx/ssl/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]